### ISSUE TITLE
Issue with input: empty Build Trigger API token specified

### ISSUE THREAD

**Issue by rami965** [DroidsOnRoids/bitrise-step-trigger-bitrise-workflow#13]
The build fails with error:
`Issue with input: empty Build Trigger API token specified`

It was building successfully, and nothing has changed. I am using the token in code tab in my project page "BUILD TRIGGER TOKEN"

This is the build URL:
https://app.bitrise.io/build/73a2ecaada656081#?tab=log

**Comment by koral--** [comment]
This is a community created step and I don't have access to private build logs.
So you need to either better describe this case or create a public project containing reproducible example.

Is it a PR build? Maybe it don't have access to sensitive token variable?

**Comment by rami965** [comment]
@koral-- Thank you for your response.
The issue is fixed but there was another one, this step doesn't seem to build the same branch as the current workflow, even after changing the "(Source) Branch to build" variable. 
This is not clear in the docs or in readme file

**Comment by koral--** [comment]
Again, could you share an example demonstrating this issue?

**Comment by rami965** [comment]
@koral-- Thank you, I was able to solve the problem by changing the "(Source) Branch to build" to the appropriate value.

**Comment by cdavie-weconnect** [comment]
We are seeing the same "empty Build Trigger API token specified" error, even though the secret is added to the step. @rami965 How did you fix that issue?

**Comment by jonathansouza-hotmart** [comment]
The same here @cdavie-weconnect and @rami965 could you share how you fixed that issue @rami965 ?

**Comment by koral--** [comment]
Are they PR builds? if so, make sure that `Expose for Pull Requests?` switch is enabled for that secret.
